"""
Django settings for tabloid_web project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n5+%q%k@6c1q0d*v7ao=8h2a-xb*o%q8&@%!e%bld$^k(6!m$k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'catalog',
    'deals',
    'stores',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tabloid_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'deals.context_processors.cart',
                'deals.context_processors.notifications',
                'deals.context_processors.location',
            ],
        },
    },
]

WSGI_APPLICATION = 'tabloid_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_I18N = True

USE_TZ = True

USE_L10N = True

LANGUAGE_CODE = 'pt-BR'

USE_THOUSAND_SEPARATOR = True

TIME_ZONE = 'America/Sao_Paulo'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Supabase Storage (S3-compatible)
# ---------------------------------------------------------------------------
# Set SUPABASE_STORAGE_BUCKET_NAME in .env to enable cloud media storage.
# Leave it unset (or empty) to fall back to local filesystem storage.
# ---------------------------------------------------------------------------
_SUPABASE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET_NAME', '')

if _SUPABASE_BUCKET:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': _SUPABASE_BUCKET,
                'access_key': os.environ['SUPABASE_STORAGE_ACCESS_KEY_ID'],
                'secret_key': os.environ['SUPABASE_STORAGE_SECRET_ACCESS_KEY'],
                'region_name': os.environ.get('SUPABASE_STORAGE_REGION', 'sa-east-1'),
                'endpoint_url': os.environ['SUPABASE_STORAGE_ENDPOINT_URL'],
                # Supabase Storage uses path-style URLs (not virtual-hosted)
                'addressing_style': 'path',
                # Files are publicly readable via Supabase policies;
                # don't generate pre-signed URLs.
                'querystring_auth': False,
                # Where inside the bucket to place uploads
                'location': 'media',
                # Custom domain so public URLs look like:
                # https://<project>.supabase.co/storage/v1/object/public/<bucket>/media/<file>
                'custom_domain': os.environ.get('SUPABASE_STORAGE_CUSTOM_DOMAIN', ''),
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
