# Generated by Django 5.2.13 on 2026-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_post_postprice_postvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('store', 'Loja verificada'), ('flyer', 'Folheto extraído')], default='store', max_length=20),
        ),
    ]
