# Generated by Django 5.2.13 on 2026-04-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13)),
                ('store_product_id', models.CharField(blank=True, max_length=100)),
                ('product_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.pricesnapshot')),
            ],
            options={
                'ordering': ['date', 'rank'],
                'unique_together': {('date', 'snapshot')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'ean'], name='catalog_pro_store_i_55c905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'store_product_id')},
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['date', 'is_featured'], name='catalog_pri_date_e0029d_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['date', 'discount_pct'], name='catalog_pri_date_899d27_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['product', 'date'], name='catalog_pri_product_39c15b_idx'),
        ),
    ]
