# Generated by Django 5.2.13 on 2026-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='price_app',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='price_credit_card_club',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='limited_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumb_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('unit', 'un'), ('kg', 'kg'), ('g', 'g'), ('l', 'L'), ('ml', 'mL')], max_length=10),
        ),
    ]
