# Generated by Django 5.2.13 on 2026-05-06 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


def backfill_supermarket(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Category.objects.filter(verticals=[]).update(verticals=['supermarket'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image_url_pricesnapshot_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='verticals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.RunPython(backfill_supermarket, reverse_code=migrations.RunPython.noop),
    ]
