# Generated by Django 5.2.13 on 2026-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to='stores/logos/'),
        ),
    ]
