# Generated by Django 5.2.13 on 2026-04-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='phone',
            new_name='telephone_1',
        ),
        migrations.RenameField(
            model_name='storeaddress',
            old_name='line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='storeaddress',
            old_name='line_2',
            new_name='address_line_2',
        ),
        migrations.AddField(
            model_name='store',
            name='has_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='has_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
