# Generated by Django 5.2.13 on 2026-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_phone_store_telephone_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vertical',
            field=models.CharField(choices=[('supermarket', 'Mercado'), ('pharmacy', 'Farmácia')], db_index=True, default='supermarket', max_length=20),
        ),
    ]
